---
- name: Stop cobbler server
  hosts: localhost
  become: True

  tasks:
    - name: Remove the existing systems
      command: cobbler system remove --name={{ item.name }}
      loop: "{{ systems_provisioned }}"

    - name: Stop services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - cobblerd
        - rsyncd
        - dhcpd
        - xinetd
        - tftp

    - name: Disable services
      service:
        name: "{{ item }}"
        enabled: no
      loop:
        - cobblerd
        - rsyncd
        - dhcpd
        - xinetd
        - tftp

